# Generated by Django 3.0.5 on 2020-04-09 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('item_type', models.CharField(max_length=20)),
                ('path', models.FilePathField(path='home/video/')),
                ('cover', models.ImageField(upload_to='')),
            ],
        ),
    ]
