# Generated by Django 3.0.5 on 2020-04-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200409_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='path',
            field=models.FileField(upload_to='video/'),
        ),
    ]
